/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.14/userguide/multi_project_builds.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

// The foojay-resolver plugin was previously used to auto-download JDKs.
// It has been removed to avoid plugin resolution failures in environments
// such as VS Code where the plugin repository may be unreachable.

rootProject.name = "ssltest"
include("app")
