/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.14/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    id("org.jetbrains.kotlin.jvm") version "1.9.22"
    // shadow
    id("com.github.johnrengelman.shadow") version "8.1.1"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

// Version catalog for dependencies
val versions = mapOf(
    "kotlin" to "1.9.22",
    "slf4j" to "2.0.11",
    "logback" to "1.5.13",
    "jackson" to "2.16.1",
    "kotlin-logging" to "3.0.5"
)

dependencies {
    // Picocli for command line argument parsing
    implementation("info.picocli:picocli:4.7.5")
    annotationProcessor("info.picocli:picocli-codegen:4.7.5")
    
    // JSON and YAML support
    implementation("com.fasterxml.jackson.core:jackson-databind:${versions["jackson"]}")
    implementation("com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:${versions["jackson"]}")
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin:${versions["jackson"]}")
    
    // Logging
    implementation("org.slf4j:slf4j-api:${versions["slf4j"]}")
    implementation("io.github.microutils:kotlin-logging:${versions["kotlin-logging"]}")
    implementation("ch.qos.logback:logback-classic:${versions["logback"]}")

    // Kotlin dependencies
    implementation("org.jetbrains.kotlin:kotlin-stdlib")
    implementation("org.jetbrains.kotlin:kotlin-reflect")

    // Testing
    testImplementation("org.jetbrains.kotlin:kotlin-test")
    testImplementation("org.junit.jupiter:junit-jupiter:5.10.2")
    testImplementation("org.junit.platform:junit-platform-launcher:1.10.2")
    testImplementation("io.mockk:mockk:1.13.9")

    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-jdk8:1.7.3")
}

// Java configuration
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(21))
    }
}

// Kotlin configuration
tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile> {
    kotlinOptions {
        jvmTarget = "21"
        freeCompilerArgs = listOf("-Xjsr305=strict")
    }
}

// Java compilation configuration
tasks.withType<JavaCompile> {
    options.compilerArgs.addAll(listOf("--enable-preview"))
}

// Application configuration
application {
    mainClass.set("org.example.SSLTestKt")
}

// Run task configuration
tasks.named<JavaExec>("run") {
    standardInput = System.`in`
    jvmArgs("--enable-preview")
}

// Testing configuration
tasks.test {
    useJUnitPlatform()
    // jvmArgs = listOf("-javaagent:${classpath.find { it.name.startsWith(\"byte-buddy-agent\") }?.absolutePath}")
    testLogging {
        events("passed", "skipped", "failed")
        showStandardStreams = true
    }
    
    // Add test execution time listener
    systemProperty("junit.platform.listener.default.class", "org.example.TestExecutionTimeListener")
}
